### ISSUE TITLE
Players can't push any entities

### ISSUE THREAD

**Issue by KyuubiFox** [gvlfm78/BukkitOldCombatMechanics#35]
Ok so i saw you had a fix for the players not being able to push ANY entities with the plugin. I have removed the plugin previously due to running into this issue. That fixed nothing they still couldnt push anything. Now i added the newest version prior to your fix and still cant push anything.... Any solutions to fixing this.
[OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/691964/OCM.zip)
Last OCM version we used. not sure which it is.

**Comment by KyuubiFox** [comment]
Anything happening with this?

**Comment by Rayzr522** [comment]
@KyuubiFox try doing `/scoreboard teams list` in-game. If it lists a team by the name of `ocmInternal`, remove it with `/scoreboard teams remove ocmInternal`.

Obviously this is a problem on the plugin end of things, but until we fix it, try those commands. This shouldn't be necessary, and it should fix this when the plugin is disabled. I have some ideas for how we could do that...

Anyways, let us know if those commands work. Have a nice day! :grin:

**Comment by KyuubiFox** [comment]
Ok i did that but still appear to be unable to push minecarts and mobs or even players http://prntscr.com/dyqnz5 
the only team left may need support for askyblock teams or something
https://www.spigotmc.org/resources/a-skyblock.1220/

**Comment by Darksiderss** [comment]
Guys i can't push entities and i checked the scoreboards list but NameTagEdit is the plugin conflicting with OCM. Also i have tried this plugin [HERE](https://www.spigotmc.org/resources/1-9-anti-collision.28770/) and it works perfectly with no problems with my NameTagEdit plugin

**Comment by gvlfm78** [comment]
@KyuubiFox @Darksiderss  I have just changed the no-collisions module to use packets instead of scoreboards in order to reduce conflicts if not eliminating them entirely, based on the plugin @Darksiderss linked.
Please try [test build #135](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/135/) or above and tell me if there still are issues with the module.
